# meta
title: 'unofficial | 吴非的个人网站'
enSubtitle: unofficial's personal website
keywords: 'unofficial, 前端, javascript, nodejs, php'
description: '吴非的个人网站，关注学习前端知识，分享工作生活中的一言一感'

# logo
logo: Unofficial's Blog
cankao: http://www.google.com/get/noto/

# index fixed image
fixedBgImgPath: assets/imgs/fixedBg.jpg

# path
homePath: assets/css/home.css
stylePath: assets/css/style.css
fontPath: assets/font/
imgPath: assets/imgs/
jsPath: assets/js/

# duoshuo
duoshuo_shortname: unofficial

# 统计
ta.qq.com: //tajs.qq.com/stats?sId=52446048
